# -*- coding: utf-8 -*-
"""NLP task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gn2qjK-pCAgn45g06cOoj7RbYj-BAtih
"""

import numpy as np
import nltk
from nltk.tokenize import word_tokenize
import spacy
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
nltk.download('punkt')
nltk.download('punkt_tab') # Added to resolve LookupError for punkt_tab
spacy.cli.download('en_core_web_sm')
nlp = spacy.load("en_core_web_sm")
# Define your corpus here, e.g.:
corpus = "This is a sample corpus for text generation. It will be used to create n-grams and train a model."
tokens = word_tokenize(corpus)
lemmatized_tokens = [token.lemma_ for token in nlp(corpus)] # Fixed: token.lemma_ and list comprehension syntax
all_tokens = tokens + lemmatized_tokens
kera_tokenizer = Tokenizer() # Fixed: Capitalized Tokenizer and renamed to avoid conflict
kera_tokenizer.fit_on_texts(all_tokens)
total_words = len(kera_tokenizer.word_index) + 1
input_sequences = []
for line in all_tokens:
  token_list = kera_tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1] # Fixed: n-gram_sequence to n_gram_sequence
    input_sequences.append(n_gram_sequence)
max_sequence_len = max(len(seq) for seq in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')
# Prepare X and Y after all sequences are generated and padded
X, Y = input_sequences[:, :-1], input_sequences[:, -1]
Y = np.array(Y)
# Model creation and training should happen once, after data preparation
model = Sequential() # Fixed: Capitalized Sequential
model.add(Embedding(total_words, 100, input_length=max_sequence_len - 1))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X, Y, epochs=10, verbose=1)